---
name: Export label config
on: [push, pull_request]

jobs:
  labels:
    runs-on: ubuntu-latest

    steps:
      - uses: EndBug/export-label-config@v1
        with:
          # This is needed if you're dealing with private repos.
          token: ${{ secrets.GITHUB_TOKEN }}

          # Set this to `true` if you want to get the raw API reponse. Defaults to `false`.
          raw-result: true

          # By default every label entry will have an `aliases` property set to an empty array.
          # It's for EndBug/label-sync, if you don't want it you cans set this to `false`
          add-aliases: true
