---
name: "🔖 Issue Labeler"
on:
  issues:
    types: [opened, edited]

permissions:
  issues: write
  contents: read

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - uses: github/issue-labeler@v3.4
        with:
          configuration-path: .github/labeler.yml
          not-before: 2020-01-15T02:54:32Z
          enable-versioned-regex: 1
          versioned-regex: 'issue_labeler_regex_version=(\d+)'
          body-missing-regex-label: "broken-template"
          repo-token: ${{ github.token }}
